FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl && \
    rm -rf /var/lib/apt/lists/*

COPY scaler/requirements.txt /app/scaler-requirements.txt
RUN pip install --no-cache-dir -r /app/scaler-requirements.txt

COPY scaler /app/scaler

CMD ["python", "-m", "scaler.main"]


