apiVersion: apps/v1
kind: Deployment
metadata:
  name: userscale-app
  namespace: userscale
  labels:
    app: userscale-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userscale-app
  template:
    metadata:
      labels:
        app: userscale-app
    spec:
      containers:
        - name: app
          image: userscale-app:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          command: ["python", "-m", "app.main"]
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 10
      nodeSelector: {}
---
apiVersion: v1
kind: Service
metadata:
  name: userscale-app
  namespace: userscale
spec:
  selector:
    app: userscale-app
  ports:
    - name: http
      port: 80
      targetPort: 8000


