apiVersion: v1
kind: ConfigMap
metadata:
  name: userscale-config
  namespace: userscale
data:
  # Enhanced scaling configuration
  ALPHA: "0.6"                    # More responsive EWMA smoothing
  MIN_REPLICAS: "1"
  MAX_REPLICAS: "20"
  USERS_TARGET_PER_POD: "10"      # Lower threshold for more aggressive scaling
  CPU_TARGET: "50"                # Lower CPU threshold
  GPU_TARGET: "60"
  LATENCY_TARGET_MS: "200"        # New latency threshold
  SCALE_UP_STEP: "2"
  SCALE_DOWN_STEP: "1"
  COOLDOWN_PERIOD: "30"           # Cooldown between scaling operations
  SYNC_PERIOD: "15"               # Check every 15 seconds
  
  # GPU monitoring configuration
  GPU_PROM_BASE: "http://prometheus:9090"
  
  # Application configuration
  MATRIX_DEFAULT_SIZE: "1000"
  GPU_WORK_DURATION_MS: "1000"