apiVersion: v1
kind: ServiceAccount
metadata:
  name: userscale-scaler
  namespace: userscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: userscale-scaler
  namespace: userscale
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status", "deployments/scale", "replicasets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userscale-scaler
  namespace: userscale
subjects:
  - kind: ServiceAccount
    name: userscale-scaler
    namespace: userscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: userscale-scaler
