apiVersion: apps/v1
kind: Deployment
metadata:
  name: userscale-scaler
  namespace: userscale
  labels:
    app: userscale-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userscale-scaler
  template:
    metadata:
      labels:
        app: userscale-scaler
    spec:
      serviceAccountName: userscale-scaler
      containers:
        - name: scaler
          image: userscale-scaler:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: userscale-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"


