apiVersion: apps/v1
kind: Deployment
metadata:
  name: userscale-scaler
  namespace: userscale
  labels:
    app: userscale-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userscale-scaler
  template:
    metadata:
      labels:
        app: userscale-scaler
    spec:
      serviceAccountName: userscale-scaler
      containers:
      - name: scaler
        image: userscale-scaler:local
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          value: "userscale"
        - name: DEPLOYMENT
          value: "userscale-app"
        - name: SERVICE_NAME
          value: "userscale-app"
        - name: APP_PORT
          value: "8000"
        - name: SYNC_PERIOD
          value: "3"
        - name: ALPHA
          value: "0.9"
        - name: MIN_REPLICAS
          value: "1"
        - name: MAX_REPLICAS
          value: "20"
        - name: USERS_TARGET_PER_POD
          value: "1"
        - name: CPU_TARGET
          value: "10"
        - name: GPU_TARGET
          value: "20"
        - name: LATENCY_TARGET_MS
          value: "50"
        - name: SCALE_UP_STEP
          value: "5"
        - name: SCALE_DOWN_STEP
          value: "1"
        - name: COOLDOWN_PERIOD
          value: "5"
        - name: GPU_PROM_BASE
          value: "http://prometheus:9090"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: Always